Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        echo "192.168.0.170  master-node" >> /etc/hosts
        echo "192.168.0.171  worker-node01" >> /etc/hosts
        echo "192.168.0.172  worker-node02" >> /etc/hosts
    SHELL
    
    config.vm.define "master" do |master|
      master.vm.box = "bento/ubuntu-18.04"
      master.vm.hostname = "master-node"
      master.vm.network "public_network", ip: "192.168.0.170", bridge: "wlp7s0"
      master.vm.provision "shell",
      	run: "always",
      	inline: "route add default gw 192.168.0.1"
      master.vm.provision "shell",
      	run: "always",
	      inline: "eval `route -n | awk '{ if ($8 ==\"wlp7s0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
      master.vm.provider "virtualbox" do |vb|
          vb.memory = 2048
          vb.cpus = 2
   # config.vm.network "forwarded_port", guest: 8080, host: 8080
   # config.vm.network "forwarded_port", guest: 8001, host: 8001
      end
      master.vm.provision "shell", path: "scripts/common.sh"
      master.vm.provision "shell", path: "scripts/master.sh"
    end

    (1..2).each do |i|
  
    config.vm.define "node0#{i}" do |node|
      node.vm.box = "bento/ubuntu-18.04"
      node.vm.hostname = "worker-node0#{i}"
      node.vm.network "public_network", ip: "192.168.0.17#{i}", bridge: "wlp7s0"
      node.vm.provision "shell",
      	run: "always", 
      	inline: "route add default gw 192.168.0.1"
      node.vm.provision "shell",
      	run: "always",
	      inline: "eval `route -n | awk '{ if ($8 ==\"wlp7s0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 1048
          vb.cpus = 1
   # config.vm.network "forwarded_port", guest: 8080, host: 8080 
      end
      node.vm.provision "shell", path: "scripts/common.sh"
      node.vm.provision "shell", path: "scripts/node.sh"
    end
    
    end
  end
